spring:
  application:
    name: stock-service
  kafka:
    topic:
      name: order_topics
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

rabbitmq:
  queue:
    name:
      stock: order_stock

server:
  port: 8081